# POD

apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
  type: frontend
  app: myapp
spec:
 containers:
  - command:
     - /bin/sh
     - -c
     - sleep 500
     - echo hello
    name: redis
    image: redis
    
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
      
 volumes:
   - name: test-volume
     emptyDir: {}


# ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myRS
 labels:
  type: frontend
  app: myapp
spec:
 template:
  metadata: # from pod
  spec: # from pod
  
 replicas: 3
 selector:
  matchLabels: # which POD to use
    type: frontend
    
  
