apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
  type: frontend
  app: myapp
spec:


 containers:
  - command:
     - /bin/sh
     - -c
     - sleep 500
     - echo hello
    name: redis
    image: redis
    
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
      
 volumes:
   - name: test-volume
     emptyDir: {}
