# POD

apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
  type: frontend
  app: myapp
  
spec:
 containers:
  - command:
     - /bin/sh
     - -c
     - sleep 500
     - echo hello
    name: redis
    image: redis
    ports:
        - containerPort: 80
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
      
 volumes:
   - name: test-volume
     emptyDir: {}


# ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myRS
 labels:
  type: rs
  app: myapp
spec:
 replicas: 3
 selector:
  matchLabels: # which POD to use
    type: frontend
 template:
  metadata: # from pod
  spec: # from pod
   containers: 
  

    
 # Deployment -- create RS as well

apiVersion: apps/v1
kind: Deployment
metadata: 
   name: nginx-depl
   labels:
     type: depapp
     app: nginx-app
 
spec: 
  replicas: 3
  selector:
   matchLabels: # which POD to use
    type: frontend
    
  template:
   metadata: # from pod
   spec: # from pod
     containers: 
     
 

 
   
   
   
